name: courses
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  lottie: ^2.1.0
  firebase_core: 2.4.0
  google_sign_in: 5.4.2
  firebase_auth: 4.2.3
  convex_bottom_bar: 3.1.0+1
  buttons_tabbar: 1.3.6
  cloud_firestore: 4.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lotties/
    - assets/images/
  uses-material-design: true

